### Importing numpy module

In [2]:
import numpy as np

### Creating a numpy array

In [2]:
arr = np.array([1,2,3,4,5,6])

In [17]:
type(arr)

numpy.ndarray

In [4]:
print(arr)
print(arr.dtype) #datatype
print(arr.dtype.itemsize)

[1 2 3 4 5 6]
int32
4


### Storing text in numpy 

In [10]:
text_arr = np.array(["Hallo", "Hola", "Hello", "Ni hao"])

In [11]:
print(text_arr)
print(text_arr.dtype) #datatype
print(text_arr.dtype.itemsize)

['Hallo' 'Hola' 'Hello' 'Ni hao']
<U6
24


### Storing Dates

In [12]:
date_arr = np.array(["2004-10-06", "2005-08-31", "2005-02-11"])

In [13]:
print(date_arr)
print(date_arr.dtype) #datatype
print(date_arr.dtype.itemsize)

['2004-10-06' '2005-08-31' '2005-02-11']
<U10
40


In [15]:
modified_arr = date_arr.astype("M")  #converts it to datetime datatype


print(modified_arr.dtype)
print(modified_arr.dtype.itemsize)

datetime64[D]
8


In [16]:
date_arr = np.array(["2004-10-06", "2005-08-31", "2005-02-11"], dtype= "M")

print(date_arr)
print(date_arr.dtype) #datatype
print(date_arr.dtype.itemsize)

['2004-10-06' '2005-08-31' '2005-02-11']
datetime64[D]
8


### Creating numpy arrays using array() method

In [72]:
nums_list = [10,20,30,40,50]
np_array = np.array(nums_list)
print(nums_list)
print(type(nums_list))
print(np_array)
print(type(np_array))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [73]:
list = [2,3,4,5]
np_arr = np.asarray(list)

print(np_arr)
type(np_arr)

[2 3 4 5]


numpy.ndarray

In [74]:
tuple = [2,3,4,5]
np_arr = np.asarray(tuple)
print(tuple)
print(np_arr)
type(np_arr)

[2, 3, 4, 5]
[2 3 4 5]


numpy.ndarray

In [22]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

np_2D_arr = np.array([row1, row2, row3])
np_2D_arr.shape

(3, 3)

In [23]:
np_2D_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating numpy arrays using arange() method

In [24]:
nums_arr = np.arange(6, 31)
print(nums_arr)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30]


In [25]:
nums_arr = np.arange(6, 32, 3)
print(nums_arr)

[ 6  9 12 15 18 21 24 27 30]


### Creating numpy arrays using ones() method

In [28]:
np_ones_arr = np.ones(16)

print(np_ones_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
np_ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np_ones_2D = np.ones((3,5))
print(np_ones_2D)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Creating numpy arrays using zeros() method

In [30]:
np_zeros_arr = np.zeros(16)

print(np_zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
np_zeros_2D = np.zeros((3,5))

print(np_zeros_2D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Creating numpy arrays using eye() method

In [34]:
# Itentity matrix
eye_arr = np.eye(5)

print(eye_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Creating numpy arrays with specific values

In [66]:
num_arr = np.full((5,3), 31)
print(num_arr)

[[31 31 31]
 [31 31 31]
 [31 31 31]
 [31 31 31]
 [31 31 31]]


### Creating numpy array of  evenly spaced values

In [69]:
arr = np.linspace(10, 55, 6) #specify the number of values reqiured
print(arr)

[10. 19. 28. 37. 46. 55.]


In [70]:
arr = np.arange(10, 55, 6) #specify the step
print(arr) 

[10 16 22 28 34 40 46 52]


### Creating numpy arrays using random.rand() method

In [36]:
rand_arr = np.random.rand(4,3)
print(rand_arr)

[[0.58256167 0.9848459  0.66514482]
 [0.43467334 0.24655758 0.04603258]
 [0.22610311 0.54332693 0.68364318]
 [0.35695621 0.51679963 0.69456595]]


In [37]:
# With Normal Distribution

rand_arr_n = np.random.randn(4,3)
print(rand_arr_n)

[[ 1.31281798  0.07823511 -0.75427038]
 [ 1.70092898 -0.53659096  1.79659382]
 [ 0.956908    0.0787828   1.00616053]
 [ 0.345365    0.50039685 -0.27920739]]


In [38]:
# Random Integer

rand_arr_int = np.random.randint(6, 31, 10)
print(rand_arr_int)

[ 8 22 20 12 26 13 24 29 13 23]


In [42]:
# Random Integer 2D

rand_arr_int = np.random.randint(6, 31, size = (3,5))
print(rand_arr_int)

[[ 9 26 19 18 29]
 [ 7 12  7 17 24]
 [ 7 13 29 26  6]]


In [44]:
for i in rand_arr_int:
    for j in i:
        print(j)

9
26
19
18
29
7
12
7
17
24
7
13
29
26
6


### Analysing the numpy array

In [41]:
rand_arr_n.shape

(4, 3)

In [40]:
rand_arr_n.ndim

2

In [75]:
rand_arr_int.size

15

In [76]:
rand_arr_int.dtype

dtype('int32')

## Adding items in a NumPy array

In [47]:
text_arr = np.array(["Hallo", "Hola", "Hello"])

text_arr= np.append(text_arr,"Ni hao")

In [48]:
text_arr

array(['Hallo', 'Hola', 'Hello', 'Ni hao'], dtype='<U6')

In [49]:
print(text_arr)

['Hallo' 'Hola' 'Hello' 'Ni hao']


In [50]:
text_arr = np.append(text_arr, ["Ohayo", "Hey"])

In [51]:
print(text_arr)

['Hallo' 'Hola' 'Hello' 'Ni hao' 'Ohayo' 'Hey']


In [53]:
zeros_arr = np.zeros((3,3))
print(zeros_arr)
print("Extended array")
extended = np.append(zeros_arr, [[1],[2],[3]], axis=1)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended array
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


### Removing items from a NumPy array

In [56]:
new_arr = np.array(["Hallo", "Hola", "Hello", "Ni hao"])
print(new_arr)
print("After Deletion")
updated_arr = np.delete(new_arr, 3)
print(updated_arr)

['Hallo' 'Hola' 'Hello' 'Ni hao']
After Deletion
['Hallo' 'Hola' 'Hello']


In [57]:
new_arr = np.array(["Hallo", "Hola", "Hello", "Ni hao"])
print(new_arr)
print("After Deletion")
updated_arr = np.delete(new_arr, [1,3])
print(updated_arr)

['Hallo' 'Hola' 'Hello' 'Ni hao']
After Deletion
['Hallo' 'Hello']


In [64]:
int_rand = np.random.randint(10, 27, size=(2,3))
print(int_rand)

print("After deletion")
int_rand = np.delete(int_rand, 1, axis=0)
print(int_rand)

[[13 10 19]
 [25 22 16]]
After deletion
[[13 10 19]]


## Mathematical Operations on a NumPy array

In [79]:
#List
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  #concatenates / joins 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [82]:
np_arr1 = np.random.randint(1,5,(2,2))
np_arr2 = np.random.randint(6,9,(2,2))

print("Array 1")
print(np_arr1)
print("Array 2")
print(np_arr2)

print("Addition")
print(np_arr1 + np_arr2)

print("Subtraction")
print(np_arr1 - np_arr2)

print("Multiplication")
print(np_arr1 * np_arr2)

print("Division")
print(np_arr1 / np_arr2)

Array 1
[[3 2]
 [4 4]]
Array 2
[[8 7]
 [8 8]]
Addition
[[11  9]
 [12 12]]
Subtraction
[[-5 -5]
 [-4 -4]]
Multiplication
[[24 14]
 [32 32]]
Division
[[0.375      0.28571429]
 [0.5        0.5       ]]


In [83]:
print(np.add(np_arr1, np_arr2))

[[11  9]
 [12 12]]


In [84]:
print(np.subtract(np_arr1, np_arr2))

[[-5 -5]
 [-4 -4]]


In [85]:
print(np.multiply(np_arr1, np_arr2))

[[24 14]
 [32 32]]


In [86]:
print(np.divide(np_arr1, np_arr2))

[[0.375      0.28571429]
 [0.5        0.5       ]]


## Numpy Array Manipulation

### Sorting Numeric arrays

In [87]:
print("unsorted array")
num_arr = np.random.randint(1, 20, 10)
print(num_arr)

unsorted array
[13  9  2 10 10 17  1  6  5  9]


In [88]:
print("Sorted array")
sorted_num_arr = np.sort(num_arr)
print(sorted_num_arr)

Sorted array
[ 1  2  5  6  9  9 10 10 13 17]


In [89]:
#2D array
print("unsorted array")
num_arr = np.random.randint(1, 20, size=(4,5))
print(num_arr)

print("Sorted array")
sorted_num_arr = np.sort(num_arr)
print(sorted_num_arr)

unsorted array
[[10 14  4 11 19]
 [ 6  4  5 13 13]
 [ 3  5  8  8  4]
 [ 9  9 12 11 12]]
Sorted array
[[ 4 10 11 14 19]
 [ 4  5  6 13 13]
 [ 3  4  5  8  8]
 [ 9  9 11 12 12]]


In [90]:
#2D array
print("unsorted array")
num_arr = np.random.randint(1, 35, 10)
print(num_arr)

print("Sorted array")
sorted_num_arr = np.sort(num_arr)
reverse_sorted_num_arr = np.flipud(sorted_num_arr)
print(reverse_sorted_num_arr)

unsorted array
[26  7  5 34  6 21  3 25 18 34]
Sorted array
[34 34 26 25 21 18  7  6  5  3]


## Reshaping the arrays

### Lower to Higher Dimensions

In [96]:
print("1D array")
num_arr = np.random.randint(1, 35, 18)
print(num_arr)

1D array
[10 31 15 32 26  6 25 19 12 22 24 12  1  6  8  6 33  6]


In [97]:
print("2D array")
num_arr = num_arr.reshape(3,6)
print(num_arr)

2D array
[[10 31 15 32 26  6]
 [25 19 12 22 24 12]
 [ 1  6  8  6 33  6]]


In [98]:
print("3D array")
num_arr = num_arr.reshape(3, 2, 3 )
print(num_arr)

3D array
[[[10 31 15]
  [32 26  6]]

 [[25 19 12]
  [22 24 12]]

 [[ 1  6  8]
  [ 6 33  6]]]


### Higher to Lower Dimensions

In [99]:
print("2D Array")
num_arr = np.random.randint(2, 31, size= (3,4))
print(num_arr)

print("1D Array")
num_arr = num_arr.reshape(12)
print(num_arr)

2D Array
[[26 11 14  6]
 [24 28 25 12]
 [ 9 16 29  5]]
1D Array
[26 11 14  6 24 28 25 12  9 16 29  5]


In [100]:
print("3D Array")
num_arr = np.random.randint(2, 131, size= (3,4,5))
print(num_arr)

print("1D Array")
num_arr = num_arr.reshape(-1)
print(num_arr)

3D Array
[[[ 16 125  18 126  98]
  [ 74 121  84 120 127]
  [121 115  42 110  17]
  [124  85 111 130  97]]

 [[106  43  46  17 105]
  [ 91 103  84  86 111]
  [124  41  35  27 115]
  [  6 105  36  44 117]]

 [[ 15 112  78  32  65]
  [ 78  44  99  67  45]
  [125  20  16  75 118]
  [ 25 108  38  44 108]]]
1D Array
[ 16 125  18 126  98  74 121  84 120 127 121 115  42 110  17 124  85 111
 130  97 106  43  46  17 105  91 103  84  86 111 124  41  35  27 115   6
 105  36  44 117  15 112  78  32  65  78  44  99  67  45 125  20  16  75
 118  25 108  38  44 108]


## Indexing and Slicing

In [101]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [103]:
print(arr[0])
print(arr[2:3])
print(arr[4:10])
print(arr[-1])
print(arr[:-1])
print(arr[2:])
print(arr[::-1])

1
[3]
[ 5  6  7  8  9 10]
10
[1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [105]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

np_2D_arr = np.array([row1, row2, row3])
print(np_2D_arr[:2,:])
print(np_2D_arr[:2,1])
print(np_2D_arr[1,2])
print(np_2D_arr[0,:])

[[1 2 3]
 [4 5 6]]
[2 5]
6
[1 2 3]


## Copying numpy arrays

In [106]:
arr = np.array([1,4,23,5,75,22,123])
print(arr)

arr1 = arr.copy()
print(arr1)
arr1[2] = 0
print(arr1)

[  1   4  23   5  75  22 123]
[  1   4  23   5  75  22 123]
[  1   4   0   5  75  22 123]


In [108]:
arr = np.array([1,4,23,5,75,22,123])
print(arr)

arr1 = arr.view()
print(arr1)
arr1[2] = 0
print(arr1)

[  1   4  23   5  75  22 123]
[  1   4  23   5  75  22 123]
[  1   4   0   5  75  22 123]


## Saving Numpy arrays

In [115]:
arr = np.array([11,22,33,44,55,66,77,88,99,00])

np.save("D:\\ML-Practice\\arrays",arr)

## Loading Numpy arrays

In [113]:
loaded_arr = np.load("arrays.npy")
print(loaded_arr)

[11 22 33 44 55 66 77 88 99  0]


## Statistical operations

### Mean

In [3]:
arr = np.array([2,4,6,8,10,12])
print(arr)
print("mean:", np.mean(arr))

[ 2  4  6  8 10 12]
mean: 7.0


In [6]:
arr_2d = np.random.randint(15, 25, size=(2,4))
print(arr_2d)
print("mean:", np.mean(arr_2d))
print("mean:", np.mean(arr_2d, axis=0))
print("mean:", np.mean(arr_2d, axis= 1))

[[19 20 18 17]
 [18 22 22 24]]
mean: 20.0
mean: [18.5 21.  20.  20.5]
mean: [18.5 21.5]


### Median

In [8]:
arr = np.array([2,4,8,10,12])
print(arr)
print("median:", np.median(arr))

[ 2  4  8 10 12]
median: 8.0


In [10]:
arr_2d = np.random.randint(15, 25, size=(2,4))
print(arr_2d)
print("median:", np.median(arr_2d))
print("median:", np.median(arr_2d, axis=0))
print("median:", np.median(arr_2d, axis= 1))

[[17 16 21 16]
 [15 16 17 17]]
median: 16.5
median: [16.  16.  19.  16.5]
median: [16.5 16.5]


### Max and Min values

In [11]:
arr = np.array([2,4,6,8,10,12])
print(arr)
print("max:", np.amax(arr))
print("min:", np.amin(arr))

[ 2  4  6  8 10 12]
max: 12
min: 2


### Standard Deviation

In [12]:
arr = np.array([2,4,6,8,10,12])
print(arr)
print("SD:", np.std(arr))

[ 2  4  6  8 10 12]
SD: 3.415650255319866


In [13]:
arr_2d = np.random.randint(15, 25, size=(2,4))
print(arr_2d)
print("SD:", np.std(arr_2d))
print("SD:", np.std(arr_2d, axis=0))
print("SD:", np.std(arr_2d, axis= 1))

[[16 20 19 16]
 [19 23 23 21]]
SD: 2.54644359843292
SD: [1.5 1.5 2.  2.5]
SD: [1.78535711 1.6583124 ]


### Correlations

In [14]:
a1 = np.array([1, 2, 4, 2.3, 9.0])
a2 = np.array([4.5, 7, 1, 0.2, 3])

print(a1)
print(a2)
print("Correlation:", np.correlate(a1,a2))

[1.  2.  4.  2.3 9. ]
[4.5 7.  1.  0.2 3. ]
Correlation: [49.96]


### Getting Unique Items and Counts

In [16]:
num = np.array([123,2,3,424,3,6,45,655,3,221,3,1,2,12,1,1,2])
print(num)
unique_items, count = np.unique(num, return_counts=True)
print(unique_items)
print(count)

[123   2   3 424   3   6  45 655   3 221   3   1   2  12   1   1   2]
[  1   2   3   6  12  45 123 221 424 655]
[3 3 4 1 1 1 1 1 1 1]


In [17]:
freq = np.asarray((unique_items, count)).T
print(freq)

[[  1   3]
 [  2   3]
 [  3   4]
 [  6   1]
 [ 12   1]
 [ 45   1]
 [123   1]
 [221   1]
 [424   1]
 [655   1]]


### Reversing a Array

In [20]:
print("Original")
arr = np.random.randint(3, 35, 10)
print(arr)
print("Reversed")
print(np.flipud(arr))

Original
[ 9 34  9 15 20 24  8 25 27 20]
Reversed
[20 27 25  8 24 20 15  9 34  9]


In [23]:
print("Original")
arr = np.random.randint(3, 35, size = (2,5))
print(arr)
print("Reversed")
print(np.fliplr(arr))

Original
[[30 29  5 10 18]
 [15 23 15 11 14]]
Reversed
[[18 10  5 29 30]
 [14 11 15 23 15]]
