# Numpy

In [2]:
#importing libraries, and aliasing

import numpy as np

In [3]:
lst=[1,2,3,4,5]
type(lst)

list

In [4]:
arr=np.array(lst)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape    #specifies the no. of rows and columns

(5,)

In [26]:
#multi nested array
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,9,5,8]
arr=np.array([l1,l2,l3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 9, 5, 8]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [9, 5, 8]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 9, 5, 8]])

### Indexing

In [62]:
#Accessing array elements
arr=np.array([1,2,3,4,5,6,7,8,9,0])

In [15]:
arr[2]

3

In [59]:
arr

array([  0,   2,   4, 100])

In [24]:
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [34]:
arr.shape

(3, 5)

In [35]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 9, 5, 8]])

In [36]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [41]:
print(arr[:,3:5])

[[4 5]
 [5 6]
 [5 8]]


In [42]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [43]:
arr[:,3:4]

array([[4],
       [5],
       [5]])

In [49]:
arr=np.arange(0,7,2)

In [50]:
arr

array([0, 2, 4, 6])

In [55]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [63]:
#copy function
#copies the given value to all the indicies
arr[3:]=100

In [64]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr1=arr

In [66]:
arr1[4:]=500
arr1

array([  1,   2,   3, 100, 500, 500, 500, 500, 500, 500])

In [67]:
arr #since arr1=arr the value is updated

array([  1,   2,   3, 100, 500, 500, 500, 500, 500, 500])

In [69]:
#this function duplicates the arr, so the values won't be updated
arr2=arr.copy()

In [73]:
arr[5:]=930
print(arr)
print(arr2)

[  1   2   3 100 500 930 930 930 930 930]
[  1   2   3 100 500 500 500 500 500 500]


In [75]:
val=30
arr>30

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [78]:
arr*2

array([   2,    4,    6,  200, 1000, 1860, 1860, 1860, 1860, 1860])

In [82]:
val=500
arr[arr>val]

array([930, 930, 930, 930, 930])

In [83]:
#create arrays and reshape
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
np.ones(4,int)

array([1, 1, 1, 1])

In [87]:
np.ones((2,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [88]:
#random distribution
np.random.rand(3,3)

array([[0.94775341, 0.92415295, 0.34566795],
       [0.088916  , 0.78612672, 0.27274589],
       [0.26870676, 0.6833176 , 0.62461945]])

In [90]:
#random normal distribution
np.random.randn(3,3)

array([[ 0.80149246,  0.28832796,  0.09457161],
       [ 2.16847814, -1.29082528,  0.2713385 ],
       [-0.72600706,  0.17363242, -0.33719592]])

In [97]:
#random int
np.random.randint(0,100,20).reshape(5,2,2)

array([[[ 1,  7],
        [78, 13]],

       [[75, 34],
        [79,  0]],

       [[69, 81],
        [72, 52]],

       [[14, 32],
        [99, 28]],

       [[40, 78],
        [40, 74]]])

In [100]:
#returns random floats within the interval
np.random.random_sample((1,5))

array([[0.83306562, 0.89825366, 0.40437581, 0.51978298, 0.30416643]])